version: '3.8'

services:
  embed-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=dev
      - MEMORY_BACKEND=local
      - SLM_IMPL=local
      - TOKEN_BUDGET=6000
      - LOG_LEVEL=INFO
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      # Mount data directory for persistence in dev
      - ./data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import httpx; httpx.get(\"http://localhost:8000/v1/healthz\")' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

